language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.3
  - jruby-19mode
  - jruby-9.0.0.0
  - jruby-head
  - ruby-head

sudo: false

addons:
  code_climate:
      repo_token: 0ddf2a14a01d14b70843d9ad37ce4e7f1ff7edd7c08aec35d5d830299342850d

before_install: gem install bundler -v 1.10.6
